module Colorless.CodeGen.Format.Json
  (
  ) where

import Pregame
import Colorless.CodeGen.Types

{-

-- colorless
reverse (a: str): str
-- arg name is req for primitive types

-- json
{
  "fn": "reverse",
  "args": {
    "a": "hello"
  }
}

"olleh"

----------------

-- colorless
age (Id Person): Years

-- json
{
  "fn": "age",
  "args": {
    "id": "some id as a string"  -- the `id` arg name is generated by the opaque name
  }
}

7

----------------

-- colorless
different (a: Id Person) (b: Id Person): bool
-- arg names are req because there's more than one of the same type as an arg.

-- json
{
  "fn": "different",
  "args": {
    "a": "a person id",
    "b": "another person id"
  }
}

true

-- colorless
circleArea Circle: f64

Circle
  center: Point f64
  radius: f64

Point a
  x: a
  y: a

-- json
{
  "fn": "circleArea",
  "args": {
    "circle": {
      "center": {
        "x": 0.0,
        "y": 0.0
      },
      "radius": 10.10
    }
  }
}

320.3114

----------------

-- colorless
Color
  Red
  Blue
  Yellow
  Green

enemy (you: Color): Color

-- json
{
  "fn": "enemy",
  "args": {
    "you": {
      "ty": "Red"
    }
  }
}

{
  "ty": "Blue"
}

----------------

-- colorless
foo (Either int str): bool

-- Json
{
  "fn": "foo",
  "args": {
    "either": {
      "ty": "Left",
      "d": [
        100
      ]
    }
  }
}

false

-}
