module Colorless.CodeGen.Format.Json
  (
  ) where

import Pregame
import Colorless.CodeGen.Types

{-

-- colorless
reverse (a: str): str
-- arg name is req for primitive types

-- json
{
  'fn': 'reverse',
  'args': {
    'a': 'hello'
  }
}

----------------

-- colorless
age (Id Person): Years

-- json
{
  'fn': 'age',
  'args': {
    'id': 'some id as a string'  -- the 'id' arg name is generated by the opaque name
  }
}

----------------

-- colorless
different (a: Id Person) (b: Id Person): bool
-- arg names are req because there's more than one of the same type as an arg.

-- json
{
  'fn': 'different',
  'args': {
    'a': 'a person id',
    'b': 'another person id'
  }
}

-}
